# Generated by Django 5.1.2 on 2024-11-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
